### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-scape-jail-university#4]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by samuelpolo59** [comment]
En el documento Wiki se ha descrito el funcionamiento de las diferentes funciones de cada prueba. Además de que cada una de las pruebas actúa en el archivo "Principal.c" como una función.
