### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-scape-jail-university#5]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by estebanhenriquez** [comment]
typedef struct
{
    char nombre[20];
    char apellido1[20];
    char apellido2[20];
    int edad;
    char work;
}integrante
Esta estructura recoge los datos del usuario (nombre, apellidos, edad y ocupación)
para crear una base de datos donde se almacena esta información
