### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-scape-jail-university#6]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by fernandoriverob** [comment]
Los ficheros empleados en este programa son todos del tipo .txt, se emplean estos ficheros para liberar espacio de memoria, pues los sudokus solución solo se emplean para comparar con el valor dado por el usuario, mientras que los ficheros de dibujo se emplean  para liberar memoria pues son las definiciones de las palabras a encontrar en la sopa de letras. Este codigo es el siguiente:
Caso de mates: 
`FILE *pfmatesX = fopen("Mates1.txt","r");
                if(pfmatesX==NULL)
                {
                    printf("\tError al abrir el fichero.\n");
                }
                else
                {
                    while(fscanf(pfmates1, "%d ", &sudokusol[i][j])!= EOF)
                    {
                        j++;
                        if(j==9)
                        {
                            i++;
                            j=0;
                        }

                    }
                }
                fclose(pfmatesX);`

Aplicación del código, aquí declaramos el puntero por el que vas recorrer el fichero y guardar ese valor en la matriz en la matriz solución correspondiente. Hay una comprobación para ver si el fichero se ha abierto correctamente o hay un error con ese mismo fichero al abrirlo por memoria insuficiente. Para guardar cada elemento empleo un bucle en el cual me cuenta hasta nueva columnas y cuando llegue a ese número de columnas se realiza un reinicio con una suma de fila, es decir, la columna se reinicia en cero y la fila se le suma un valor, para poder guardar los 81 valores.

Por otra parte, la prueba de dibujo, el código sirve para liberar memoria y se emplea para copiar todo lo que hay en el fichero y poner de tal forma que represente lo del fichero. A su vez, cuento el numero de caracteres y convierto los punteros de cada uno de ellos en vectores. 

Por último, se cerrará ambos ficheros.

**Comment by fernandoriverob** [comment]
Luego hay un par de ficheros más en el programa, pero es el mismo cambiando los parámetros ofrecidos, ya que en un caso es el de partida guardada, que contiene información de los jugadores así como las pruebas que han pasado y por otro lado tengo el de partida nueva donde el fichero se crea desde cero y sirve para escribir los datos de cada jugador.
En cada prueba hay un puntero, que apunta a este mismo fichero 'Misdatos.txt' donde se han guardado los datos de los jugadores y se guardará si han pasado cada una de las distintas pruebas o no. Con este método si quieren continuar con la prueba otro día pueden.

Para partida nueva:
FILE *pf;
    pf=fopen("Misdatos.txt", "w");
    fprintf(pf, "Nombre del equipo: %s\n", equipo);
    for(i=0; i<n; i++)
    {
        fprintf(pf, "Jugador %d:\nNombre: %s\nApellido 1: %s\nApellido 2: %s\nEdad: %d\nEst/Tra: %c\n", i+1, jugador[i].nombre, jugador[i].apellido1, jugador[i].apellido2, jugador[i].edad, jugador[i].work);
    }
    fclose(pf);

Para cada una de las distintas pruebas:

pf=fopen("Misdatos.txt", "a");
    fprintf(pf, "pX = %d", pruebaX);
    fclose(pf);

Para una partida guardara se abrirá el fichero y se analizará cuantas pruebas han pasado.
