### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-scape-jail-university#8]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by estebanhenriquez** [comment]
El menu se inicia y pide datos al usuario (nombre, apellidos, situación laboral, integrantes del equipo y nombre de este.)
Después, estos datos se guardan en un fichero llamado Misdatos.txt, el programa puede ser ejecutado para mas de un jugador al mismo tiempo. Adjuntamos capturas del código del menú.
![MENU3](https://user-images.githubusercontent.com/61050049/170685515-46dd6ad4-5c70-4055-9215-97a8104067e8.png)

![MENU2](https://user-images.githubusercontent.com/61050049/170685372-099d9d13-7a73-4755-ab05-ba39363ec3da.png)
![MENU1](https://user-images.githubusercontent.com/61050049/170685410-3ea73375-d680-4a0b-bccd-684c02d32588.png)
![MENU33](https://user-images.githubusercontent.com/61050049/170685450-be410798-8122-40d7-988f-b0a06f54ca27.png)
